### ISSUE TITLE
Meat issue

### ISSUE THREAD

**Issue by duckduckstab1** [Seamusmario/BonziWORLD-Revived-Classic#1]
C:\Users\no\update\server>node index.js
Created new settings file.

 Welcome to BonziWORLD!
 Time to meme!
 ----------------------
 Server listening at port 3000
(node:12200) Warning: Accessing non-existent property 'io2' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

C:\Users\no\update\server>

**Comment by Seamusmario** [comment]
Fixed

**Comment by duckduckstab1** [comment]
Thank you.
